require 'rubygems'
require 'bundler/setup'

require 'rake/clean'

gem_name     = 'remote_syslog'
package_name = 'papertrail-remote_syslog'
version      = '1.6.14'

release = ENV['GO_PIPELINE_COUNTER'] || ENV['RELEASE'] || 1

CLEAN.include 'pkg'
CLEAN.include 'jailed-root'

fake_gem_home = "jailed-root/opt/local/#{package_name}"
fake_gem_bin  = File.join(fake_gem_home, 'bin')

task :init do
  mkdir_p "log"
  mkdir_p "pkg"
  mkdir_p "jailed-root"
end

task :install do
  sh(%Q{
       export GEM_HOME=#{fake_gem_home}
       export GEM_PATH=#{fake_gem_home}
       unset RUBYOPT
       gem install #{gem_name} --version #{version} --bindir=#{fake_gem_home}/bin --no-ri --no-rdoc
  })
end

task :build do
  Dir["#{fake_gem_bin}/*"].each do |f|
    sh(%Q{sed --in-place "s%require \'rubygems\'%ENV[\'GEM_PATH\']= \'/opt/local/#{package_name}\' + \':\' + ENV[\'GEM_PATH\'].to_s\\nrequire \'rubygems\'%" #{f}})
  end

  require 'erb'

  mkdir_p 'jailed-root/etc/init.d'

  ERB.new(File.read('init-script.erb'), nil , '-').tap do |template|
    File.open("jailed-root/etc/init.d/papertrail", 'w') do |f|
      f.puts(template.result)
    end
  end

  chmod 0755, "jailed-root/etc/init.d/papertrail"

end

task :package do
  description_string = %Q{Lightweight daemon to tail one or more log files and transmit UDP syslog messages to a remote syslog host (centralized log aggregation). Generates UDP packets itself instead of depending on a system syslog daemon, so it doesn't affect system-wide logging configuration.}
  mkdir_p 'jailed-root/etc'
  File.open("jailed-root/etc/papertrail.yml", 'w') do |f|
    f.puts %Q{# File generated by #{package_name} rpm, modify it there.}
    f.puts %Q{# For examples see https://github.com/papertrail/remote_syslog/tree/master/examples}
    f.puts %Q{files:}
    f.puts %Q{  - /dev/null}
    f.puts %Q{destination:}
    f.puts %Q{  host: example.papertrailapp.com}
    f.puts %Q{  port: 12345}
  end
  sh(%Q{bundle exec fpm -s dir -t rpm --force --package pkg/#{package_name}-#{version}-#{release}.x86_64.rpm --name #{package_name} -a x86_64 --version "#{version}" -C jailed-root --depends 'ruby-1.9.3-p484' --verbose --rpm-user root --rpm-group root --config-files etc/papertrail.yml --maintainer snap-ci@thoughtworks.com --vendor snap-ci@thoughtworks.com --url http://snap-ci.com --description #{Shellwords.escape(description_string)} --iteration #{release} --license 'https://github.com/papertrail/remote_syslog/blob/v#{version}/LICENSE' .})
end

desc "build and package #{package_name}-#{version}"
task :all => [:clean, :init, :install, :build, :package]

desc "build all #{package_name}"
task :default => :all
